### ISSUE TITLE
Version 1.9.0-1.9.3 doesn't compile on FreeBSD 13.1 with -DNDEBUG defined

### ISSUE THREAD

**Issue by diizzyy** [dreibh/netperfmeter#4]
Hi,

If you try to compile with -DNDEBUG defined build fails with

```
src/tools.cc:1140:25: error: use of undeclared identifier 'uniform'
   const double value = uniform(0.0, (double)0xffffffff);
```

https://github.com/dreibh/netperfmeter/blob/master/src/tools.cc#L1138

Reference: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266721

This is also true using the latest release 1.9.3

LLVM/clang version 13.0.0

Best regards,
Daniel

**Comment by diizzyy** [comment]
@dreibh
Are you still interested in maintaining your ports in FreeBSD's package repo? All your ports are outdated

**Comment by dreibh** [comment]
Hi,

On 10/20/22 11:08, Daniel Engberg wrote:
>
> @dreibh <https://github.com/dreibh>
> Are you still interested in maintaining your ports in FreeBSD's 
> package repo? All your ports are outdated
>
Sure, I am going to provide an update.

-- 
Best regards / Mit freundlichen Grüßen / Med vennlig hilsen

=======================================================================
  Thomas Dreibholz

  SimulaMet — Simula Metropolitan Centre for Digital Engineering
  Centre for Resilient Networks and Applications
  Pilestredet 52
  0167 Oslo, Norway
-----------------------------------------------------------------------
  ***@***.***
  Homepage:http://simula.no/people/dreibh
=======================================================================

**Comment by dreibh** [comment]
The FreeBSD port now has the up-to-date version 1.9.7.
